# Generated by Django 3.2.5 on 2021-11-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_categoryseven'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
